name: setup-env
description: "Setup environment"

inputs:
  python-version:
    description: Python version to install
    default: "3.11"

runs:
  using: composite

  steps:
    - name: Setup mise
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

    - name: Install Python
      run: uv python install ${{ matrix.python-version }}

    - shell: bash
      run: uv sync --link-mode copy --locked
